using ReconDashboards.Core.Schema;

namespace ReconDashboards.Core.Modeling;

/// <summary>
/// The fixed shape of a model-declared VIRTUAL calendar table. Date tables key
/// as "#date.{Name}" — '#' can never appear in a real schema-qualified key, so
/// they can never collide with (or shadow) catalog tables. At compile time each
/// referenced date table becomes a "dt_{Name}" CTE generated by the dialect;
/// nothing is ever introspected or persisted for them.
/// </summary>
public static class DateTableSchema
{
    public const string SchemaName = "#date";
    public const string KeyPrefix = "#date.";
    public const string DateKeyColumn = "date_key";

    /// <summary>Default range start when <see cref="DateTableDef.RangeStart"/> is null.</summary>
    public static readonly DateOnly DefaultRangeStart = new(2015, 1, 1);

    /// <summary>Default range end when <see cref="DateTableDef.RangeEnd"/> is null: Dec 31 of next year per the injected clock.</summary>
    public static DateOnly DefaultRangeEnd(TimeProvider clock) => new(clock.GetUtcNow().Year + 1, 12, 31);

    public static bool IsDateTableKey(string tableKey) =>
        tableKey.StartsWith(KeyPrefix, StringComparison.Ordinal);

    /// <summary>CTE name; always dialect-quoted at the point of emission.</summary>
    public static string CteName(DateTableDef dateTable) => "dt_" + dateTable.Name;

    /// <summary>Synthesizes the catalog entry the resolver/validator sees. date_key is the primary key, so many-to-one onto it is proven.</summary>
    public static TableSchema Build(DateTableDef dateTable) => new(
        SchemaName, dateTable.Name, TableKind.View, RowEstimate: null, Comment: null,
        Columns:
        [
            new ColumnSchema(DateKeyColumn, 1, "date", NormalizedType.Date, IsNullable: false, Comment: null),
            new ColumnSchema("year", 2, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("quarter", 3, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("month", 4, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("month_name", 5, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("week", 6, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("day", 7, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("day_name", 8, "text", NormalizedType.Text, IsNullable: false, Comment: null),
        ],
        PrimaryKey: [DateKeyColumn],
        UniqueConstraints: []);
}
