using ReconDashboards.Core.Schema;

namespace ReconDashboards.Core.Modeling;

/// <summary>
/// The fixed shape of a model-declared VIRTUAL calendar table. Date tables key
/// as "#date.{Name}" — '#' can never appear in a real schema-qualified key, so
/// they can never collide with (or shadow) catalog tables. At compile time each
/// referenced date table becomes a "dt_{Name}" CTE generated by the dialect;
/// nothing is ever introspected or persisted for them.
/// </summary>
public static class DateTableSchema
{
    public const string SchemaName = "#date";
    public const string KeyPrefix = "#date.";
    public const string DateKeyColumn = "date_key";

    /// <summary>Default range start when <see cref="DateTableDef.RangeStart"/> is null.</summary>
    public static readonly DateOnly DefaultRangeStart = new(2015, 1, 1);

    /// <summary>Default range end when <see cref="DateTableDef.RangeEnd"/> is null: Dec 31 of next year per the injected clock.</summary>
    public static DateOnly DefaultRangeEnd(TimeProvider clock) => new(clock.GetUtcNow().Year + 1, 12, 31);

    public static bool IsDateTableKey(string tableKey) =>
        tableKey.StartsWith(KeyPrefix, StringComparison.Ordinal);

    /// <summary>CTE name; always dialect-quoted at the point of emission.</summary>
    public static string CteName(DateTableDef dateTable) => "dt_" + dateTable.Name;

    /// <summary>
    /// Synthesizes the catalog entry the resolver/validator sees. date_key is
    /// the primary key, so many-to-one onto it is proven. Column set (v2):
    /// calendar parts, unabbreviated names, ISO year/week, weekday facts
    /// (day_of_week/week_start honor <see cref="DateTableDef.WeekStartDay"/>;
    /// is_weekend is always Sat/Sun), sortable labels (year_month sorts
    /// lexicographically = chronologically), month anchors, and fiscal_*
    /// columns (equal to calendar values when fiscalYearStartMonth is 1 —
    /// always emitted).
    /// </summary>
    public static TableSchema Build(DateTableDef dateTable) => new(
        SchemaName, dateTable.Name, TableKind.View, RowEstimate: null, Comment: null,
        Columns:
        [
            new ColumnSchema(DateKeyColumn, 1, "date", NormalizedType.Date, IsNullable: false, Comment: null),
            new ColumnSchema("year", 2, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("quarter", 3, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("month", 4, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("month_name", 5, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("week", 6, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("day", 7, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("day_name", 8, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("month_name_full", 9, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("day_name_full", 10, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("day_of_week", 11, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("day_of_year", 12, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("iso_year", 13, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("iso_week", 14, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("is_weekend", 15, "boolean", NormalizedType.Boolean, IsNullable: false, Comment: null),
            new ColumnSchema("year_month", 16, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("month_year_label", 17, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("quarter_label", 18, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("year_quarter", 19, "text", NormalizedType.Text, IsNullable: false, Comment: null),
            new ColumnSchema("month_start", 20, "date", NormalizedType.Date, IsNullable: false, Comment: null),
            new ColumnSchema("week_start", 21, "date", NormalizedType.Date, IsNullable: false, Comment: null),
            new ColumnSchema("days_in_month", 22, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("fiscal_year", 23, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("fiscal_quarter", 24, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
            new ColumnSchema("fiscal_month", 25, "integer", NormalizedType.Integer, IsNullable: false, Comment: null),
        ],
        PrimaryKey: [DateKeyColumn],
        UniqueConstraints: []);
}
