CREATE TABLE IF NOT EXISTS "__RcdMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___RcdMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_dashboards (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "ModelId" integer,
        "LayoutJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboards" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_data_models (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataSourceName" character varying(64) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "DefinitionJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_data_models" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_query_audit (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(128) NOT NULL,
        "DataSourceName" character varying(64) NOT NULL,
        "ModelId" integer,
        "SpecJson" text NOT NULL,
        "SqlHash" character varying(64) NOT NULL,
        "RowCount" integer NOT NULL,
        "ElapsedMs" integer NOT NULL,
        "Succeeded" boolean NOT NULL,
        "ErrorCode" character varying(64),
        "ExecutedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_query_audit" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_dashboards_OwnerUserId_IsDeleted" ON rcd_dashboards ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_dashboards_OwnerUserId_Name" ON rcd_dashboards ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_data_models_OwnerUserId_IsDeleted" ON rcd_data_models ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_data_models_OwnerUserId_Name" ON rcd_data_models ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_query_audit_ExecutedAtUtc" ON rcd_query_audit ("ExecutedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804132930_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE TABLE rcd_alerts (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerUserId" character varying(128) NOT NULL,
        "DashboardId" integer,
        "Name" character varying(128) NOT NULL,
        "SpecJson" jsonb NOT NULL,
        "Operator" character varying(8) NOT NULL,
        "Threshold" numeric(28,8) NOT NULL,
        "Recipients" character varying(2048) NOT NULL,
        "EveryMinutes" integer NOT NULL,
        "CooldownMinutes" integer NOT NULL,
        "Enabled" boolean NOT NULL,
        "LastEvaluatedUtc" timestamp without time zone,
        "LastFiredUtc" timestamp without time zone,
        "LastValue" numeric(28,8),
        "CreatedUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_alerts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE TABLE rcd_subscriptions (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "ScheduleKind" character varying(16) NOT NULL,
        "IntervalMinutes" integer,
        "TimeOfDayMinutesUtc" integer,
        "DayOfWeekUtc" integer,
        "Recipients" character varying(2048) NOT NULL,
        "Format" character varying(8) NOT NULL,
        "Enabled" boolean NOT NULL,
        "LastRunUtc" timestamp without time zone,
        "CreatedUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_subscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_subscriptions_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_DashboardId" ON rcd_alerts ("DashboardId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_Enabled_LastEvaluatedUtc" ON rcd_alerts ("Enabled", "LastEvaluatedUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_LastFiredUtc" ON rcd_alerts ("LastFiredUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_OwnerUserId" ON rcd_alerts ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_DashboardId" ON rcd_subscriptions ("DashboardId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_Enabled_LastRunUtc" ON rcd_subscriptions ("Enabled", "LastRunUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_OwnerUserId" ON rcd_subscriptions ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260805181636_SubscriptionsAndAlerts', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE TABLE rcd_dashboard_activity (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "Action" character varying(64) NOT NULL,
        "DetailJson" jsonb,
        "AtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboard_activity" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_dashboard_activity_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE TABLE rcd_dashboard_shares (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "CanEditLayout" boolean NOT NULL DEFAULT FALSE,
        "CanManagePages" boolean NOT NULL DEFAULT FALSE,
        "CanEditCharts" boolean NOT NULL DEFAULT FALSE,
        "GrantedByUserId" character varying(128) NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboard_shares" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_dashboard_shares_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE INDEX "IX_rcd_dashboard_activity_DashboardId_AtUtc" ON rcd_dashboard_activity ("DashboardId", "AtUtc" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE UNIQUE INDEX "IX_rcd_dashboard_shares_DashboardId_UserId" ON rcd_dashboard_shares ("DashboardId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE INDEX "IX_rcd_dashboard_shares_UserId" ON rcd_dashboard_shares ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260811182420_DashboardSharesAndActivity', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE TABLE rcd_global_optouts (
        "Email" character varying(320) NOT NULL,
        "OptedOutUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_global_optouts" PRIMARY KEY ("Email")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE TABLE rcd_subscription_dispatches (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SubscriptionId" integer NOT NULL,
        "SubscriptionName" character varying(200) NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "DashboardId" integer NOT NULL,
        "Trigger" character varying(10) NOT NULL,
        "RequestedBy" character varying(64),
        "StartedUtc" timestamp without time zone NOT NULL,
        "FinishedUtc" timestamp without time zone,
        "Status" character varying(12) NOT NULL,
        "Error" character varying(1000),
        CONSTRAINT "PK_rcd_subscription_dispatches" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE TABLE rcd_subscription_optouts (
        "SubscriptionId" integer NOT NULL,
        "Email" character varying(320) NOT NULL,
        "OptedOutUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_subscription_optouts" PRIMARY KEY ("SubscriptionId", "Email")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE TABLE rcd_subscription_dispatch_recipients (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DispatchId" bigint NOT NULL,
        "Email" character varying(320) NOT NULL,
        "Status" character varying(12) NOT NULL,
        "Attempts" integer NOT NULL DEFAULT 0,
        "Error" character varying(1000),
        "SentUtc" timestamp without time zone,
        "OpenedUtc" timestamp without time zone,
        "OpenCount" integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_rcd_subscription_dispatch_recipients" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_subscription_dispatch_recipients_rcd_subscription_dispa~" FOREIGN KEY ("DispatchId") REFERENCES rcd_subscription_dispatches ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE INDEX "IX_rcd_subscription_dispatch_recipients_DispatchId" ON rcd_subscription_dispatch_recipients ("DispatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE INDEX "IX_rcd_subscription_dispatches_Status_StartedUtc" ON rcd_subscription_dispatches ("Status", "StartedUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    CREATE INDEX "IX_rcd_subscription_dispatches_SubscriptionId_StartedUtc" ON rcd_subscription_dispatches ("SubscriptionId", "StartedUtc" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819134939_SubscriptionDispatchesAndOptOuts') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260819134939_SubscriptionDispatchesAndOptOuts', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819151209_ShareMoveAndDeleteRights') THEN
    ALTER TABLE rcd_dashboard_shares ADD "CanDeleteContent" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819151209_ShareMoveAndDeleteRights') THEN
    ALTER TABLE rcd_dashboard_shares ADD "CanMoveTiles" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819151209_ShareMoveAndDeleteRights') THEN
    UPDATE rcd_dashboard_shares
    SET "CanMoveTiles" = "CanEditLayout",
        "CanDeleteContent" = ("CanEditCharts" OR "CanManagePages");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819151209_ShareMoveAndDeleteRights') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260819151209_ShareMoveAndDeleteRights', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819212113_SubscriptionEmailContent') THEN
    ALTER TABLE rcd_subscriptions ADD "ContentJson" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260819212113_SubscriptionEmailContent') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260819212113_SubscriptionEmailContent', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260820161054_UserSettings') THEN
    CREATE TABLE rcd_user_settings (
        "UserId" character varying(128) NOT NULL,
        "SettingsJson" jsonb NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_user_settings" PRIMARY KEY ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260820161054_UserSettings') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260820161054_UserSettings', '10.0.8');
    END IF;
END $EF$;
COMMIT;

