CREATE TABLE IF NOT EXISTS "__RcdMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___RcdMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_dashboards (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "ModelId" integer,
        "LayoutJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboards" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_data_models (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataSourceName" character varying(64) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "DefinitionJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_data_models" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_query_audit (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(128) NOT NULL,
        "DataSourceName" character varying(64) NOT NULL,
        "ModelId" integer,
        "SpecJson" text NOT NULL,
        "SqlHash" character varying(64) NOT NULL,
        "RowCount" integer NOT NULL,
        "ElapsedMs" integer NOT NULL,
        "Succeeded" boolean NOT NULL,
        "ErrorCode" character varying(64),
        "ExecutedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_query_audit" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_dashboards_OwnerUserId_IsDeleted" ON rcd_dashboards ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_dashboards_OwnerUserId_Name" ON rcd_dashboards ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_data_models_OwnerUserId_IsDeleted" ON rcd_data_models ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_data_models_OwnerUserId_Name" ON rcd_data_models ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_query_audit_ExecutedAtUtc" ON rcd_query_audit ("ExecutedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804132930_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

