CREATE TABLE IF NOT EXISTS "__RcdMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___RcdMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_dashboards (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "ModelId" integer,
        "LayoutJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboards" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_data_models (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataSourceName" character varying(64) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Description" character varying(512),
        "DefinitionJson" jsonb NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "IsShared" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_data_models" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE TABLE rcd_query_audit (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(128) NOT NULL,
        "DataSourceName" character varying(64) NOT NULL,
        "ModelId" integer,
        "SpecJson" text NOT NULL,
        "SqlHash" character varying(64) NOT NULL,
        "RowCount" integer NOT NULL,
        "ElapsedMs" integer NOT NULL,
        "Succeeded" boolean NOT NULL,
        "ErrorCode" character varying(64),
        "ExecutedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_query_audit" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_dashboards_OwnerUserId_IsDeleted" ON rcd_dashboards ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_dashboards_OwnerUserId_Name" ON rcd_dashboards ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_data_models_OwnerUserId_IsDeleted" ON rcd_data_models ("OwnerUserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_rcd_data_models_OwnerUserId_Name" ON rcd_data_models ("OwnerUserId", "Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    CREATE INDEX "IX_rcd_query_audit_ExecutedAtUtc" ON rcd_query_audit ("ExecutedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260804132930_InitialCreate') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260804132930_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE TABLE rcd_alerts (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerUserId" character varying(128) NOT NULL,
        "DashboardId" integer,
        "Name" character varying(128) NOT NULL,
        "SpecJson" jsonb NOT NULL,
        "Operator" character varying(8) NOT NULL,
        "Threshold" numeric(28,8) NOT NULL,
        "Recipients" character varying(2048) NOT NULL,
        "EveryMinutes" integer NOT NULL,
        "CooldownMinutes" integer NOT NULL,
        "Enabled" boolean NOT NULL,
        "LastEvaluatedUtc" timestamp without time zone,
        "LastFiredUtc" timestamp without time zone,
        "LastValue" numeric(28,8),
        "CreatedUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_alerts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE TABLE rcd_subscriptions (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "OwnerUserId" character varying(128) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "ScheduleKind" character varying(16) NOT NULL,
        "IntervalMinutes" integer,
        "TimeOfDayMinutesUtc" integer,
        "DayOfWeekUtc" integer,
        "Recipients" character varying(2048) NOT NULL,
        "Format" character varying(8) NOT NULL,
        "Enabled" boolean NOT NULL,
        "LastRunUtc" timestamp without time zone,
        "CreatedUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_subscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_subscriptions_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_DashboardId" ON rcd_alerts ("DashboardId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_Enabled_LastEvaluatedUtc" ON rcd_alerts ("Enabled", "LastEvaluatedUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_LastFiredUtc" ON rcd_alerts ("LastFiredUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_alerts_OwnerUserId" ON rcd_alerts ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_DashboardId" ON rcd_subscriptions ("DashboardId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_Enabled_LastRunUtc" ON rcd_subscriptions ("Enabled", "LastRunUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    CREATE INDEX "IX_rcd_subscriptions_OwnerUserId" ON rcd_subscriptions ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260805181636_SubscriptionsAndAlerts') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260805181636_SubscriptionsAndAlerts', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE TABLE rcd_dashboard_activity (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "Action" character varying(64) NOT NULL,
        "DetailJson" jsonb,
        "AtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboard_activity" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_dashboard_activity_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE TABLE rcd_dashboard_shares (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DashboardId" integer NOT NULL,
        "UserId" character varying(128) NOT NULL,
        "CanEditLayout" boolean NOT NULL DEFAULT FALSE,
        "CanManagePages" boolean NOT NULL DEFAULT FALSE,
        "CanEditCharts" boolean NOT NULL DEFAULT FALSE,
        "GrantedByUserId" character varying(128) NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_rcd_dashboard_shares" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_rcd_dashboard_shares_rcd_dashboards_DashboardId" FOREIGN KEY ("DashboardId") REFERENCES rcd_dashboards ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE INDEX "IX_rcd_dashboard_activity_DashboardId_AtUtc" ON rcd_dashboard_activity ("DashboardId", "AtUtc" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE UNIQUE INDEX "IX_rcd_dashboard_shares_DashboardId_UserId" ON rcd_dashboard_shares ("DashboardId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    CREATE INDEX "IX_rcd_dashboard_shares_UserId" ON rcd_dashboard_shares ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__RcdMigrationsHistory" WHERE "MigrationId" = '20260811182420_DashboardSharesAndActivity') THEN
    INSERT INTO "__RcdMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260811182420_DashboardSharesAndActivity', '10.0.8');
    END IF;
END $EF$;
COMMIT;

